// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6AVHn6S1qN0L2-YZINVx-bCkmR35FF5I',
    appId: '1:626247571177:android:2438f5b9971d8aecf24278',
    messagingSenderId: '626247571177',
    projectId: 'metizcinema-5734a',
    storageBucket: 'metizcinema-5734a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz369FZ_nEXGgjHWky6klD5s62-h056xg',
    appId: '1:626247571177:ios:13adfa55a12a1b08f24278',
    messagingSenderId: '626247571177',
    projectId: 'metizcinema-5734a',
    storageBucket: 'metizcinema-5734a.appspot.com',
    androidClientId: '626247571177-kpnv5of6dqr7aao42rpgqu507t04h252.apps.googleusercontent.com',
    iosClientId: '626247571177-k50qc5asovdsrint3gge59kn5b5ufbhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.metizCinema',
  );
}
